name:             Brewski
url:              https://github.com/tiaanduplessis/hexo-theme-brewski

menu:
  Home:           /
  About:          /about
  Archives:       /archives
  GitHub:         https://github.com/Ivan-F/

favicon:          /favicon.svg
logo:             /logo.svg

# Disqus shortname
disqus:

# Analytics
google_analytics:

# Copyright Infomation
copyright:
  since:
  name:
  url:
